providers = ["java"]

[variables]
NIXPACKS_BUILD_DIR = "backend/user-management-service"

[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = ["cd /app/backend/user-management-service && mvn clean package -DskipTests -Dmaven.test.skip=true"]
