providers = ["java"]

[variables]
NIXPACKS_BUILD_DIR = "backend/user-management-service"

[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = ["cd /app/backend/user-management-service && mvn clean package -DskipTests -Dmaven.test.skip=true"]

[phases.start]
cmd = "cd /app/backend/user-management-service && java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar target/user-management-service-0.0.1-SNAPSHOT.jar"
