services:
  # Frontend Service (Angular) - Fixed to serve browser directory
  - type: web
    name: aria-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm install -g serve && npm run build && cp dist/frontend/browser/index.csr.html dist/frontend/browser/index.html && echo "Created index.html:" && ls -la dist/frontend/browser/index.html
    startCommand: cd frontend && npx serve -s dist/frontend/browser -p $PORT --no-clipboard --single
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .

  # Speech Service (Python) - KEEP INTACT
  - type: web
    name: aria-speech-service
    env: python
    plan: free
    buildCommand: pip install fastapi uvicorn pydantic
    startCommand: uvicorn main_simple:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8001"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: speech-service

  # Adaptive Engine Service (Python) - KEEP INTACT
  - type: web
    name: aria-adaptive-engine
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8002"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: adaptive-engine

  # Analytics Service (Python) - KEEP INTACT
  - type: web
    name: aria-analytics-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8003"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: ai-services/analytics-service
