services:
  # Speech Service (Python) - Simplified for Python 3.13 compatibility
  - type: web
    name: aria-speech-service
    runtime: python
    plan: free
    buildCommand: pip install fastapi uvicorn pydantic
    startCommand: uvicorn main_simple:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8001
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: speech-service

  # Adaptive Engine Service (Python)
  - type: web
    name: aria-adaptive-engine
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8002
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: adaptive-engine

  # Analytics Service (Python)
  - type: web
    name: aria-analytics-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8003
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: ai-services/analytics-service

databases:
  # Optional: PostgreSQL database (can use Supabase instead)
  # - name: aria-postgres
  #   databaseName: aria_db
  #   user: aria_user
  #   plan: free
