services:
  # Frontend Service (Angular) - KEEP INTACT
  - type: web
    name: aria-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm install -g serve && npm run build
    startCommand: cd frontend && npx serve -s dist/frontend -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .

  # User Management Service (Spring Boot) - RECONFIGURED
  - type: web
    name: aria-user-management-v2
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: supabase
      - key: DATABASE_URL
        value: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&cachePrepStmts=false&useServerPrepStmts=false&rewriteBatchedStatements=false&prepareThreshold=0&preparedStatementCacheSize=0&preparedStatementCacheSqlLimit=0&ApplicationName=ARIA-User-Management"
      - key: DB_USERNAME
        value: "postgres.deqfzxsmuydhrepyiagq"
      - key: DB_PASSWORD
        value: "CoolLife@AriaDB"
      - key: UPSTASH_REDIS_HOST
        value: "renewing-falcon-41265.upstash.io"
      - key: UPSTASH_REDIS_PORT
        value: "6379"
      - key: UPSTASH_REDIS_PASSWORD
        value: "AaExAAIncDE3NTczYWIxNDNjYjA0NzI2YWQ2NmY0ZTZjZTg5Y2IyMXAxNDEyNjU"
      - key: JWT_SECRET
        value: "kV7pL9zR3mX1tU5qW8bC2yJ6fH4nE0sDmA3gK9xZ2vF8uQ4tY7rP1wE6iO5sL0hN"
      - key: CORS_ORIGINS
        value: "https://aria-frontend.onrender.com"
    healthCheckPath: /api/auth/actuator/health
    autoDeploy: false
    rootDir: backend/user-management-service

  # Interview Orchestrator Service (Spring Boot) - RECONFIGURED
  - type: web
    name: aria-interview-orchestrator-v2
    env: docker  
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: supabase
      - key: DATABASE_URL
        value: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&cachePrepStmts=false&useServerPrepStmts=false&rewriteBatchedStatements=false&prepareThreshold=0&preparedStatementCacheSize=0&preparedStatementCacheSqlLimit=0&ApplicationName=ARIA-Interview-Orchestrator"
      - key: DB_USERNAME
        value: "postgres.deqfzxsmuydhrepyiagq"
      - key: DB_PASSWORD
        value: "CoolLife@AriaDB"
      - key: UPSTASH_REDIS_HOST
        value: "renewing-falcon-41265.upstash.io"
      - key: UPSTASH_REDIS_PORT
        value: "6379"
      - key: UPSTASH_REDIS_PASSWORD
        value: "AaExAAIncDE3NTczYWIxNDNjYjA0NzI2YWQ2NmY0ZTZjZTg5Y2IyMXAxNDEyNjU"
      - key: USER_MGMT_URL
        value: "https://aria-user-management-v2.onrender.com"
      - key: CORS_ORIGINS
        value: "https://aria-frontend.onrender.com"
      - key: JWT_SECRET
        value: "kV7pL9zR3mX1tU5qW8bC2yJ6fH4nE0sDmA3gK9xZ2vF8uQ4tY7rP1wE6iO5sL0hN"
    healthCheckPath: /api/interview/actuator/health
    autoDeploy: false
    rootDir: backend/interview-orchestrator-service

  # Speech Service (Python) - KEEP INTACT
  - type: web
    name: aria-speech-service
    env: python
    plan: free
    buildCommand: pip install fastapi uvicorn pydantic
    startCommand: uvicorn main_simple:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8001"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: speech-service

  # Adaptive Engine Service (Python) - KEEP INTACT
  - type: web
    name: aria-adaptive-engine
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8002"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: adaptive-engine

  # Analytics Service (Python) - KEEP INTACT
  - type: web
    name: aria-analytics-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8003"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    rootDir: ai-services/analytics-service
