services:
  # Angular SSR Frontend
  - type: web
    name: aria-frontend
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run serve:ssr:frontend
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    rootDir: frontend

  # Speech Service (Python)
  - type: web
    name: aria-speech-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8001
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: speech-service

  # Adaptive Engine Service (Python)
  - type: web
    name: aria-adaptive-engine
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8002
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: adaptive-engine

  # Analytics Service (Python)
  - type: web
    name: aria-analytics-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8003
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    rootDir: ai-services/analytics-service

databases:
  # Optional: PostgreSQL database (can use Supabase instead)
  # - name: aria-postgres
  #   databaseName: aria_db
  #   user: aria_user
  #   plan: free
