services:
  - type: web
    name: aria-user-management-v2
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/PrajwalRamannaVenkatesh/ARIA
    branch: main
    rootDir: backend/user-management-service
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: neon
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: jdbc:postgresql://ep-muddy-truth-ad583n4q-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&ApplicationName=ARIA-User-Management
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_SxyCtjKD16EU
      - key: JWT_SECRET
        value: kV7pL9zR3mX1tU5qW8bC2yJ6fH4nE0sDmA3gK9xZ2vF8uQ4tY7rP1wE6iO5sL0hN
      - key: SPRING_REDIS_URL
        value: rediss://default:AaExAAIncDE3NTczYWIxNDNjYjA0NzI2YWQ2NmY0ZTZjZTg5Y2IyMXAxNDEyNjU@renewing-falcon-41265.upstash.io:6379
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: workwithrvprajwal@gmail.com
      - key: SMTP_PASSWORD
        value: vclhowpwtmopdqdz
      - key: CORS_ORIGINS
        value: https://aria-frontend-fs01.onrender.com
      - key: JPA_DDL_AUTO
        value: none
    # buildCommand: handled by Dockerfile multi-stage build
    # startCommand: handled by Dockerfile ENTRYPOINT
    healthCheckPath: /actuator/health
    autoDeploy: true
